### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by dliviya** [UBC-DSCI/ubc-dsci-minor-faq#10]
Please write your question about the UBC Data Science minor program or admission process here. 

In the application that the faculty of science makes us do in additional the one we did for you we need the minor advisors signature. How do we get the minor advisors signature since everything is online? Additionally who is the Data Science minor advisor? Another thing I'm not sure about (and I asked science advising) is that we need to say when we are going to take each of the classes for the minor however we dont know if those classes will even be offered in those terms. So I am confused on how to fill that bit out.

Thank you!

**Comment by Lourenzutti** [comment]
Hi @dliviya 

I am the Data Science minor advisor. 
You can bypass my signature for now, and submit your application with your Major Advisor's signature only. We will be in touch with FoS after admission and provide our signature directly to them. (But you do need to fill in our form to be considered). 

Let me know if you have any further questions.

Best,
