### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by KevinSaigon** [UBC-DSCI/ubc-dsci-minor-faq#11]
For Science students, we are supposed to upload our course form with the minor's advisor signature. Is this possible for this minor as we technically still need to get admitted.

**Comment by Lourenzutti** [comment]
Hi @KevinSaigon, 

for now, you can bypass the Minor Advisor's signature. You can submit only the major signature. We will be in contact with the FoS after the admission process. 

Let me know if you have any further questions.

Best,
