### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by luckyberen** [UBC-DSCI/ubc-dsci-minor-faq#13]
Hi! I noticed that CPSC 330 is one of the upper-level requirements for the minor in DSCI. I also noticed that CPSC 340 is in the Discipline-specific data science courses category. I'm thinking of studying further about machine learning in grad school further, so I plan to take CPSC 340 because I have heard that it contains deeper content. In this case, do I have to take both CPSC 330 and CPSC 340?

**Comment by Lourenzutti** [comment]
Hi @luckyberen,

Great question! The answer is yes. CPSC 330 is required, even if you take CPSC 340. There are some important Data Science topics in CPSC 330 that are absent in CPSC 340. 

Let me know if you have any further questions. 

Best,
