### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by KevinW404** [UBC-DSCI/ubc-dsci-minor-faq#14]
Hello, my name is Kevin, and I had a few question about the Data Science Minor!

1. For the general BSc application form for a minor, I noticed there was a "Proposed courses for minor" section. While I know the courses I'm interested in, I'm unsure about when they are offered so I don't know what to put in for the "Term and Session" section. Can I fill that part in under the assumption they're available in each winter semester, or is there more information on this?
2. Resolved
3. When asking for a signature, do I just need to send a pdf of my completed form with the signature portion blank? 

Thank you very much for reading my questions!

**Comment by Lourenzutti** [comment]
Hi @KevinW404, 

That is a great question!

1. STAT 301 will be Sept 2021 (term 1) and DSCI 310, 320 and CPSC 368 will be Jan 2022 (term 2). CPSC 330 will run in Term 1 and (likely) in Term 2 as well. 
2. Resolved.
3. The signature of DS Minor advisor you can leave it blank. However, you must acquire the signature of your major advisor. 

I hope this helps. Let me know if you have further questions. 

Best,
