### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by mandyxu36** [UBC-DSCI/ubc-dsci-minor-faq#18]
Hi, I'm a third-year commerce student looking to apply to the data science minor in September 2021. My anticipated graduation year is 2023. I'm wondering if your team is also getting in contact with the Sauder School of Business regarding similar inquiries with arts students (eligibility, needing signature of science advisor for the minor application form), or should I reach out to my home faculty directly?

Thank you in advance!

**Comment by Lourenzutti** [comment]
Hi @mandyxu36 

We haven't been in contact with Sauder School of Business. 
You can reach out to your home faculty directly. 
But, please do not hesitate to let us know if you run into trouble, and we can open some lines of communication with them.

Let me know if you have any further questions.

Best,
