### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by ProInterrupter** [UBC-DSCI/ubc-dsci-minor-faq#19]
If my specialization is in Computer Engineering or Electrical Engineering, am I still eligible for this minor?
 
What's the difference between CPSC304 and CPSC368?  Can I take CPSC404 using CPSC368 instead of 304?

**Comment by Lourenzutti** [comment]
Hi @ProInterrupter, 

Absolutely! The minor is open to any specialization. 
CPSC 368 is a new database course being developed with a focus on Data Science. 
To take CPSC 404, you will need 304. 

Please, let me know if you have further questions. 

Best,

**Comment by ProInterrupter** [comment]
Hi @Lourenzutti,

thank you for replying back !!!

The reason why I asked ECE students are eligible for this minor is because it says that one can't do a minor if the content of the minor has significant overlap with your major. I guess CE (or EE) do not have significant overlap with this minor or are you guys ok with the overlap?

If one has the choice to take CPSC304 or CPSC368, what would you recommend?

**Comment by Lourenzutti** [comment]
Hi @ProInterrupter 

I don't think the overlap will be a problem, as students from Stats and CS are eligible to do the minor. 

About CPSC 304 or CPSC 368, it depends. If you are interested in CPSC 404, you will need 304. 
If you are looking to take only one course in database that will prepare you to use databases effectively, I'd 
say CPSC 368 would be a good option. 

Hope that helps. 

Best,
