### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by zhouyusen-github** [UBC-DSCI/ubc-dsci-minor-faq#2]
I want to know more details about DSCI 310, DSCI 320, I can not find any information about these two courses in ubc website.

**Comment by ttimbers** [comment]
Great question! These will be soon added to the UBC course calendar, but are not yet there. Here's the calendar descriptions for now:

**DSCI 310 Reproducible and trustworthy workflows for data science**
Data science methods to automate the running and testing of code and analytic reports, manage data analysis software dependencies, package and deploy software for data analysis, and collaborate with others using version control.
**Credits:** 3 
**Pre-reqs:** DSCI 100 and either (a) one of CPSC 203, CPSC 210 or CPEN 221 or (b) MATH 210 and one of CPSC 107, CPSC 110.

**DSCI 320 Visualization for Data Science** 
Analysis, design, and implementation of static and interactive visual representations. Visualization literacy. Data communication. Exploratory Data Analysis. Application of theoretical principles to visualization development.
**Credits:** 3
**Pre-reqs:** STAT 201 and one of CPSC 203, CPSC 210, or CPEN 221.


We will add these the the Data Science Minor website until they are available in the calendar.
