### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by dliviya** [UBC-DSCI/ubc-dsci-minor-faq#20]
Hello,
I applied to the data science minor and I was just wondering when we would find out if we were admitted or not? It must have mentioned it in the application but I forgot what the date was, so sorry!

Thank you

**Comment by Lourenzutti** [comment]
Hi @dliviya 

We do not have firm dates yet. 
But you probably hear back from us before registration opens (i.e., at some point in June).
