### ISSUE TITLE
Registering for UBC Data Science Courses Outside of Minor

### ISSUE THREAD

**Issue by eyskim** [UBC-DSCI/ubc-dsci-minor-faq#21]
Hi everyone,

I wanted to ask if the DSCI 300-level courses will be available for registration for students outside of the minor program.

For example, I am part of BCS and am not eligible for any minors. However, I want to take these courses to fill my elective/bridging-module requirements.

Thanks!

**Comment by dennis-fan** [comment]
This is a great question and I wonder the same, having taken DSCI100 and STATS201, I'd like to continue exploring data science as part of my BCS journey

**Comment by eyskim** [comment]
Closing this as I think my question has been answered in: https://github.com/UBC-DSCI/ubc-dsci-minor-faq/issues/12
