### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by mandyxu36** [UBC-DSCI/ubc-dsci-minor-faq#24]
Hi there,

I'm wondering when STAT 301 will be offered? I don't see the course listed for Winter Session 2021. 

Thanks,
Mandy

**Comment by Lourenzutti** [comment]
Hi @mandyxu36,

Yes, it will be offered in the winter session 2021. 
(We found out today that it wasn't published yet -- should appear to you soon)


Let me know if you have any further questions.
