### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by eyskim** [UBC-DSCI/ubc-dsci-minor-faq#26]
Hello,

Hope all is well! I was wondering how registration will be handled for DSCI 320 for non-minor students. For example I'm a BCS student that can't take the minor but would like to take the course in 2021W2.

Specifically, I've registered for the lecture section (https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-section&dept=DSCI&course=320&section=201) but am unable to register for the labs because the seats are restricted. Is there a possibility of getting kicked out of the course despite being registered?

Best,
Eric

**Comment by Lourenzutti** [comment]
Hi @eyskim 

sorry for the delay. There was a bit of a complication with the registration. 
Therefore we made the seats restricted to give priority to the minor students. 

We will start registering the minor students soon and, if there are seats left, these seats will be unrestricted and students on the waitlist will get registered. 

Let me know if you have further questions. 

Cheers,
