### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by TheAMIZZguy** [UBC-DSCI/ubc-dsci-minor-faq#28]
I noticed CPSC 310 and DSCI 310 are together on the exclusion list. Would taking CPSC 310 instead of DSCI 310 count for the DSCI 310 requirement of the minor?

**Comment by Lourenzutti** [comment]
Hi @TheAMIZZguy 

No, sorry. 
The only course that will count towards the minor is DSCI 310. 
So you might need to take both.

Let me know if you have further questions.

Cheers,
