### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by TimothyZG** [UBC-DSCI/ubc-dsci-minor-faq#29]
Hi,

I'm a faculty of science student going into my second year with a combined major in computer science and statistics, I noticed that although STAT301, DSCI310, and DSCI320 are restricted to DSCI minor students, there are still quite a few seats left. Now to my understanding, most of the course scheduling process have been completed, and I happen to have met all these courses' pre-reqs, so just wondering if the seats will open up to students outside of the DSCI minor once all students in the program are done registering for courses? If so, is there a waitlist for those courses above?

I did try to apply for the data science minor, but unfortunately the faculty of science does not allow first-year students to apply for minors:( would definitely apply this year.

Anyway, thanks for replying, have a nice day.
Timothy

**Comment by Lourenzutti** [comment]
Hi @TimothyZG 

yes, the seats will be opened for students outside DSCI once the DSCI students have been registered (this process is still ongoing -- but should finish soon). 

So you should register for the waitlist in these courses (yes, there are waitlists) and if you have the prereqs, and you are high on the waitlist you should get in.

Let me know if you have further questions.

Cheers,
   Rodolfo
