### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by Maplelei1** [UBC-DSCI/ubc-dsci-minor-faq#3]
Hello, 

I have not taken DSCI 100 but wish to do so in the summer before the start of September 1st. I have read in your FAQ that this is acceptable. Thus, on my application form I had no choice but to write 0 for my DSCI 100 grade. Would this be alright or cause my application to be tossed? 

Thank you.

**Comment by Lourenzutti** [comment]
Hi Maple Lei,

thank you very much for your interest in the new Minor in Data Science.
Don't worry, your application will not be tossed because you put 0 on DSCI 100. 
However, if your application is approved, you need to obtain the minimum grade in DSCI 100 to stay in the program. 

Cheers!
