### ISSUE TITLE
UBC Data Science Minor Application Question

### ISSUE THREAD

**Issue by achinth-b** [UBC-DSCI/ubc-dsci-minor-faq#30]
Hey there, I'm a BSc Student  of computer science and statistics (combined major) and the CS department and Science advising has not been helpful in connecting me with my major advisor so I can get the signature to send in my final application. With the date looming to August 4th, I am currently panicking, trying to get the signature so I can pass in my application. I have filled the form and the application - it's just a matter of getting their approval. 

Is there anyone here who can help me connect me to my major advisor? I really want to shoot my best shot for this opportunity.  Here are my student details: 

Student number: 39210653
Major: Combined Major in Computer Science and Statistics
Year Started: 2018W

Thank you so much for your time to read and help me through this. Cheers!

**Comment by Lourenzutti** [comment]
Hi Achinth, 

I'm very sorry for the delay. Have you been able to get the approval?
