### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by navss23** [UBC-DSCI/ubc-dsci-minor-faq#31]
Hello, 
I am a first year engineering student joining in this fall. I wanted to know if i need to take some pre req course now , to be selected or given preference for the data science minor in my future degree. Help would be appreciated !

**Comment by Lourenzutti** [comment]
Hi, thank you for your interest in the minor.

The prerequisites to apply for the minor can be found [here](https://datascience.ubc.ca/minor)

Let me know if you have more questions.
