### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by chrisp-6** [UBC-DSCI/ubc-dsci-minor-faq#34]
Please write your question about the UBC Data Science minor program or admission process here. 

Hello, 

I'm wondering if there are any plans to have some of the required courses run during the summer terms? 

thanks

**Comment by Lourenzutti** [comment]
HI, we have some of the required courses running in the summer (e.g., DSCI 100, STAT 201). 
But not all the courses.

Let us know if you have further questions. 

Cheers,
    Rodolfo
