### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by dorukyvz** [UBC-DSCI/ubc-dsci-minor-faq#35]
Please write your question about the UBC Data Science minor program or admission process here. 

Before you ask a question, please read our current [FAQ page](https://ubc-dsci.github.io/ubc-dsci-minor-faq/) to see if your question has already been asked and answered 😄

Hello,

My name is Doruk Yavuz, I am a CPSC Major at UBC.

Since the very beginning of my degree, I was interested in pursuing a career in Data Science and have recently learned of the Data Science Minor offered at UBC. Had the minor been offered at the start of my degree, I would surely have pursued it.

Right now, I have about 18 credits left to take as electives and thought that completing the Data Science Minor would be an efficient way to fulfill this requirement. I have already taken all, if not most CPSC courses required for the Data Science Minor already.

I am currently eligible to register for courses as a 4th year CPSC Major in Bachelor of Arts and 3rd year CPSC Major in Bachelor of Science. I would like to know what the next processes would be to declare the minor.

Best regards,
Doruk Yavuz

**Comment by Lourenzutti** [comment]
Hi Doruk, 

thank you for your interest in the DSCI minor. 
As long as you 

(1) satisfy the prereqs for admission (see them here: https://datascience.ubc.ca/minor) 
(2) is a second or third-year student

you can apply for the minor. 

Cheers,
     Rodolfo
