### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by alexlin519** [UBC-DSCI/ubc-dsci-minor-faq#4]
Hi, right now I am a second-year maths student who is so interested in applying for the DS minor.
But I didn't take DSCI 100 and the summer course DSCI 100 is full. 
I will be a 3rd student in September 2021. What should I do?

**Comment by Lourenzutti** [comment]
Hi, thank you for the interest in the DS minor!

Unfortunately, DSCI 100 is a hard requirement to apply for the minor.
However, the number of seats available for DSCI 100 has increased by 10%. I just checked it [here](https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-section&dept=DSCI&course=100&section=002)
and there are seats available. So, I think you can still get a seat in the Summer offering, and apply for the minor 😄
