### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by ratanawang** [UBC-DSCI/ubc-dsci-minor-faq#41]
Hello! I am currently doing a combined major in computer science and statistics, which [requires me to take CPSC 310](https://www.calendar.ubc.ca/Vancouver/index.cfm?tree=12,215,410,421). I plan to apply for a Data Science minor during the 2023 intake. According to the [credit exclusion lists](https://www.calendar.ubc.ca/Vancouver/index.cfm?tree=12,215,410,414), the credit I will receive for CPSC 310 overlaps with that of DSCI 310—does this mean that I can fulfill [item 3(i) of the DSCI minor's upper-level requirements](https://datascience.ubc.ca/minor) with CPSC 310? Thank you very much in advance! :)

**Comment by ttimbers** [comment]
No, CPSC 310 cannot be used to fulfill item 3(i) of the DSCI minor's upper-level requirements. Even though the courses are credit excluded, one can still take both. CPSC 310 could count towards the major degree, and DSCI 310 could count towards the minor degree.

**Comment by ratanawang** [comment]
Noted—thank you for the clarification!
