### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by Lovey1001** [UBC-DSCI/ubc-dsci-minor-faq#44]
Hi, I am a second-degree student and I am enrolled in B.Sc with a 2nd-yr standing. I am registered in the COGS major, wanting to go into the Computational Intelligence and Design stream.

So, I had a request regarding registering for DSCI 100 course for my current degree that I want to pursue. Since I am a second-degree student, I had to submit a checklist for what courses can transfer from my previous institution. I already submitted the checklist 3 weeks ago and I have completed the following pre-requisite courses: **MATH 12**

The section that I would like to register for is DSCI 100 001 (preferably) or DSCI 100 008. I am currently on the waitlist as well.

However, as I am registering for the DSCI course, it keeps giving me an error saying that I cannot register as I have not done the pre-reqs. Now, I don't know how long it will take for the Science Advising to get back to me regarding the checklist and classes are filling up fast, I was hoping you can grant me access to register for them in the meantime. Until, I get a confirmation back. This way I can still take the courses and meet my pre-reqs for the classes for my current degree I am pursuing. 
If you can get back to me ASAP, that would be much appreciated! Thank you.

**Comment by Lourenzutti** [comment]
Hi, please contact me with your contact email. 

The DSCI 100 sections are full, so you are correct to register on the waitlist. 
I can't move you from the waitlist to the course. 

As for the error you're seeing (is it for DSCI 100? or another DSCI course?) 
DSCI 100 should give you a warning only.
