### ISSUE TITLE
When to apply to Science Advising: Science Minor

### ISSUE THREAD

**Issue by Maplelei1** [UBC-DSCI/ubc-dsci-minor-faq#5]
Hello! I have just applied to UBC's Data Science minor and filled out the application that asks for a percentage in 
DSCI 100 and another CPSC course. I am wondering when I should apply to UBC Science Advising: Minor in another 
Science specialization. Would that be after I am accepted to the Data Science minor or should I email my major and minor advisors for approval now? 

Thank you!

**Comment by Lourenzutti** [comment]
Hi, that's great! Thank you for applying for the minor.

It is important that you complete any requirements for admission into a minor from your home faculty. So, at this point, I think it is best to contact your minor advisor sooner than later.

Best,
