### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by luckyberen** [UBC-DSCI/ubc-dsci-minor-faq#6]
Please write your question about the UBC Data Science minor program or admission process here. 

Do I have to complete STAT 201 before applying DSCI minor?

Before you ask a question, please read our current [FAQ page](https://ubc-dsci.github.io/ubc-dsci-minor-faq/) to see if your question has already been asked and answered 😄

**Comment by Lourenzutti** [comment]
Hi! 

Thank you for your interest in the DS minor. 
No, you don't need to have completed STAT 201 to apply 😄 . 
It is a required course to complete the minor, but not to apply! 👍 

Best,
