### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by tanmaythakral** [UBC-DSCI/ubc-dsci-minor-faq#7]
Please write your question about the UBC Data Science minor program or admission process here. 

Before you ask a question, please read our current [FAQ page](https://ubc-dsci.github.io/ubc-dsci-minor-faq/) to see if your question has already been asked and answered 😄

Hello,
I was looking into applying into the dsci minor. I'm a first year going into the second year with all the lower level reqs fulfilled. But I don't have a specialization yet because the applications don't open until June. I will most likely have a specialization by September. What should I do in this case ?
Should I fill the application with specialization as undeclared as of now?

Thank you

**Comment by Lourenzutti** [comment]
Hi @tanmaythakral,
Thank you very much for your interest in the DS minor and
I am sorry for the delay to get to your question. 

That depends on what faculty you are in. 
Unfortunately, the Faculty of Science does not allow first-year students to apply for a minor. They require applicants to be second- or third-year students.  So, if you are in the faculty of science, you need to wait till next year. If you are enrolled in a Faculty other than science, you need to check the requirements. 

In that case, If your faculty allows you to apply for a minor in the first year, indicate this in the form. You can say something like "specialization not defined yet -- Faculty of ....." and we will look into your application in detail. 

Please let me know if you have any questions.
