### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by chloezzy** [UBC-DSCI/ubc-dsci-minor-faq#8]
Hello,

I am wondering if I am taking DSCI100 this summer term, what I should enter in the text field for "Grade in DSCI 100" in the application form.

Thank you!

**Comment by Lourenzutti** [comment]
Hi, thanks for the interest in the minor!

I think you should be able to write that in the application form. Say something like "taking it in the summer". 

Cheers!

**Comment by chloezzy** [comment]
Hi!

Thanks for the answer. However, it only allows us to enter a valid number. Should I put 0 there?

**Comment by ttimbers** [comment]
I have fixed the survey so you can enter what @Lourenzutti suggested instead of 0.
